project:
  type: website

website:
  title: ""
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        href: teaching.qmd

format:
  html:
    theme: cosmo
    toc: false