---
title: "Publications"
---

## Peer-Reviewed Articles

Jürgens, E. (2025).  
Deficit Aversion as a Path to Higher Debt: Sovereign Debt Dynamics in a Stock-Flow Consistent Model with Public Capital. *Review of Political Economy*, 38(1), 286–316.  
[Read article](https://www.tandfonline.com/doi/full/10.1080/09538259.2025.2544150)

---

## Dissertation

Jürgens, E. (2025).
*Essays on the Political Economy of Public Investment and Debt.* Doctoral thesis, University of Bamberg.
[Read dissertation](https://fis.uni-bamberg.de/handle/uniba/110156)

---

## Book Chapters

Rietzler, K., Watt, A., & Jürgens, E. (2023).  
Germany Lacks Political Will to Finance Needed Public Investment Boost.  
In F. Cerniglia, F. Saraceno, & A. Watt (Eds.),  
*Financing Investment in Times of High Public Debt: 2023 European Public Investment Outlook* (pp. 51–68).  
Cambridge, UK: Open Book Publishers.  
[PDF](https://books.openbookpublishers.com/10.11647/obp.0386.pdf)

Dullien, S., Jürgens, E., & Watzka, S. (2020).  
Public Investment in Germany: The Need for a Big Push.  
In F. Cerniglia & F. Saraceno (Eds.), *A European Public Investment Outlook* (pp. 49–62).  
Cambridge, UK: Open Book Publishers.  
[PDF](https://library.oapen.org/bitstream/handle/20.500.12657/39722/9781800640139.pdf?sequence=1#page=73)

## Other Publications

Henze, L. T., Jürgens, E., & Paetz, C. (2022).  
Einstellungen zur öffentlichen Infrastruktur und zum Investitionsbedarf im Regionalvergleich:  
Ergebnisse einer repräsentativen Online-Befragung.  
*IMK Policy Brief*, 129.  
[PDF](https://www.boeckler.de/fpdf/HBS-008383/p_imk_pb_129_2022.pdf)

Dullien, S., Jürgens, E., Paetz, C. & Watzka, S. (2021).  
Wachstums- und Verschuldungseffekte einer kreditfinanzierten öffentlichen Investitionsoffensive.  
*Wirtschaftsdienst*, 101, 700–705.  
[Read article](https://doi.org/10.1007/s10273-021-3003-5)


## Working Papers

Gechert, S., & Jürgens, E. (2025).  
Passing the Partisan Filter: Political Narratives, Partisan Bias and Opinions on Public Finances.  
*IMK Working Paper*, 227.  
[PDF](https://www.imk-boeckler.de/fpdf/HBS-009239/p_imk_wp_227_2025.pdf)

Jürgens, E. (2022).  
The Effects of Fiscal Rules on Public Investment over the Cycle.  
*FMM Working Paper*, 84.  
[PDF](https://www.imk-boeckler.de/fpdf/HBS-008482/p_fmm_imk_wp_84_2022.pdf)

---
